version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./data:/var/www/html
    cap_add:
      - NET_ADMIN
